server:
    port: 8080
spring:
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
    freemarker:
        template-loader-path:
        - /templates/
        - file:./templates/
        cache: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mblog?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root

    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ./indexes
        open-in-view: true

    servlet:
        multipart:
            max-file-size: 5MB

    mail:
        host: smtp.xxx.com
        username: example@xxx.com
        password: xxxxxx
        port: 465
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true
                    starttls:
                            enable: true
                            required: true
#域名
site.website: http://localhost:8081

site.store.root: /data/mblog
# 存储模式, 可选值 absolute / relative
site.store.repo: relative
site.store.size: 2

# 是否开启资源域名
site.store.domain: false

# ---------------------------------
# 资源域名, resource.domain : true 是有效
# 配置域名, 将域名的根目录指向 store.root 配置的地址
# ---------------------------------
site.store.host: http://localhost:8080/mblog